-- theme/generators/i3.lua

local function generate(theme)
  local out = {}

  local function line(s)
    table.insert(out, s or "")
  end

  line("# Generated by theme/build.lua")
  line("# Do not edit this file directly.")
  line("# Edit theme/themes/penrose.lua or theme/generators/i3.lua instead.")
  line()

  line("set $mod " .. theme.i3.mod)
  line("set $terminal " .. theme.apps.terminal)
  line("set $browser " .. theme.apps.browser)
  line("set $launcher " .. theme.apps.launcher)
  line()

  line("font pango:" .. theme.fonts.ui .. " " .. theme.fonts.size)
  line()

  line("# Startup")
  line("exec --no-startup-id dex --autostart --environment i3")
  line("exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork")
  line("exec --no-startup-id nm-applet")
  line("exec_always --no-startup-id ~/.config/desktop/wallpaper.sh")
  line("exec_always --no-startup-id ~/.config/polybar/launch.sh")
  line()

  line("# Media keys")
  line("set $refresh_i3status killall -SIGUSR1 i3status")
  line("bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status")
  line("bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status")
  line("bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status")
  line("bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status")
  line()

  line("# Mouse / floating behavior")
  line("floating_modifier $mod")
  line("tiling_drag modifier titlebar")
  line()

  line("# Gaps / borders")
  line("default_border pixel " .. theme.i3.border_width)
  line("default_floating_border pixel " .. theme.i3.border_width)
  line("gaps inner " .. theme.i3.gaps_inner)
  line("gaps outer " .. theme.i3.gaps_outer)
  line()

  line("# Window colors")
  line("client.focused          " ..
    theme.colors.border .. " " ..
    theme.colors.border .. " " ..
    theme.colors.bg .. " " ..
    theme.colors.border .. " " ..
    theme.colors.border
  )

  line("client.focused_inactive " ..
    theme.colors.bg_alt .. " " ..
    theme.colors.bg_alt .. " " ..
    theme.colors.fg_alt .. " " ..
    theme.colors.bg_alt .. " " ..
    theme.colors.bg_alt
  )

  line("client.unfocused        " ..
    theme.colors.bg_alt .. " " ..
    theme.colors.bg_alt .. " " ..
    theme.colors.muted .. " " ..
    theme.colors.bg_alt .. " " ..
    theme.colors.bg_alt
  )

  line("client.urgent           " ..
    theme.colors.urgent .. " " ..
    theme.colors.urgent .. " " ..
    theme.colors.bg .. " " ..
    theme.colors.urgent .. " " ..
    theme.colors.urgent
  )
  line()

  line("# Launch / close")
  line("bindsym $mod+Return exec $terminal")
  line("bindsym $mod+space exec --no-startup-id $launcher")
  line("bindsym $mod+Shift+q kill")
  line()

  line("# Focus")
  line("bindsym $mod+j focus left")
  line("bindsym $mod+k focus down")
  line("bindsym $mod+l focus up")
  line("bindsym $mod+semicolon focus right")
  line("bindsym $mod+Left focus left")
  line("bindsym $mod+Down focus down")
  line("bindsym $mod+Up focus up")
  line("bindsym $mod+Right focus right")
  line()

  line("# Move windows")
  line("bindsym $mod+Shift+j move left")
  line("bindsym $mod+Shift+k move down")
  line("bindsym $mod+Shift+l move up")
  line("bindsym $mod+Shift+semicolon move right")
  line("bindsym $mod+Shift+Left move left")
  line("bindsym $mod+Shift+Down move down")
  line("bindsym $mod+Shift+Up move up")
  line("bindsym $mod+Shift+Right move right")
  line()

  line("# Layout")
  line("bindsym $mod+h split h")
  line("bindsym $mod+v split v")
  line("bindsym $mod+f fullscreen toggle")
  line("bindsym $mod+s layout stacking")
  line("bindsym $mod+w layout tabbed")
  line("bindsym $mod+e layout toggle split")
  line("bindsym $mod+Shift+space floating toggle")
  line("bindsym $mod+a focus parent")
  line()

  line("# Workspaces")
  for _, ws in ipairs(theme.workspaces) do
    line("set $ws" .. ws.key .. " \"" .. ws.name .. "\"")
  end

  line()

  for _, ws in ipairs(theme.workspaces) do
    line("bindsym $mod+" .. ws.key .. " workspace number $ws" .. ws.key)
  end

  line()

  for _, ws in ipairs(theme.workspaces) do
    line("bindsym $mod+Shift+" .. ws.key .. " move container to workspace number $ws" .. ws.key)
  end

  line()

  line("# Reload / restart / exit")
  line("bindsym $mod+Shift+c reload")
  line("bindsym $mod+Shift+r restart")
  line([[bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"]])
  line()

  line([[mode "resize" {]])
  line("        bindsym j resize shrink width 10 px or 10 ppt")
  line("        bindsym k resize grow height 10 px or 10 ppt")
  line("        bindsym l resize shrink height 10 px or 10 ppt")
  line("        bindsym semicolon resize grow width 10 px or 10 ppt")
  line()
  line("        bindsym Left resize shrink width 10 px or 10 ppt")
  line("        bindsym Down resize grow height 10 px or 10 ppt")
  line("        bindsym Up resize shrink height 10 px or 10 ppt")
  line("        bindsym Right resize grow width 10 px or 10 ppt")
  line()
  line([[        bindsym Return mode "default"]])
  line([[        bindsym Escape mode "default"]])
  line([[        bindsym $mod+r mode "default"]])
  line("}")
  line()
  line([[bindsym $mod+r mode "resize"]])

  return table.concat(out, "\n") .. "\n"
end

return generate
