-- theme/generators/polybar.lua

local function generate(theme)
  return string.format([[
; Generated by theme/build.lua
; Do not edit this file directly.

[colors]
background = %s
background-alt = %s
foreground = %s
foreground-alt = %s
muted = %s
accent = %s
urgent = %s
warning = %s
success = %s

[bar/main]
width = 100%%
height = 24
radius = 0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
line-color = ${colors.accent}

border-size = 0
padding-left = 2
padding-right = 2

module-margin-left = 1
module-margin-right = 1

font-0 = %s:size=%d;2

modules-left = i3
modules-center = date
modules-right = pulseaudio memory cpu

cursor-click = pointer
cursor-scroll = ns-resize

wm-restack = i3
override-redirect = false

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

label-focused = %%name%%
label-focused-background = ${colors.accent}
label-focused-foreground = ${colors.background}
label-focused-padding = 2

label-unfocused = %%name%%
label-unfocused-foreground = ${colors.foreground-alt}
label-unfocused-padding = 2

label-visible = %%name%%
label-visible-foreground = ${colors.accent}
label-visible-padding = 2

label-urgent = %%name%%
label-urgent-background = ${colors.urgent}
label-urgent-foreground = ${colors.background}
label-urgent-padding = 2

[module/date]
type = internal/date
interval = 1

date = %%a %%b %%d
time = %%I:%%M %%p

label = %%date%%  %%time%%
label-foreground = ${colors.accent}

[module/cpu]
type = internal/cpu
interval = 2
label = CPU %%percentage%%%%
label-foreground = ${colors.foreground-alt}

[module/memory]
type = internal/memory
interval = 2
label = RAM %%percentage_used%%%%
label-foreground = ${colors.foreground-alt}

[module/pulseaudio]
type = internal/pulseaudio

format-volume = VOL <label-volume>
label-volume = %%percentage%%%%
format-volume-foreground = ${colors.foreground-alt}

label-muted = muted
label-muted-foreground = ${colors.muted}
]],
    theme.colors.bg,
    theme.colors.bg_alt,
    theme.colors.fg,
    theme.colors.fg_alt,
    theme.colors.muted,
    theme.colors.accent,
    theme.colors.urgent,
    theme.colors.warning,
    theme.colors.success,
    theme.fonts.ui,
    theme.fonts.bar_size
  )
end

return generate
