-- theme/generators/rofi.lua

local function generate(theme)
  return string.format([[
/* Generated by theme/build.lua */
/* Do not edit this file directly. */

* {
  bg: %s;
  bg-alt: %s;
  fg: %s;
  muted: %s;
  accent: %s;

  font: "%s %d";
}

window {
  width: %s;
  border: %dpx;
  border-color: @accent;
  border-radius: %dpx;
  background-color: @bg;
}

mainbox {
  background-color: @bg;
  padding: 14px;
}

inputbar {
  background-color: @bg-alt;
  text-color: @fg;
  border-radius: %dpx;
  padding: 10px;
  margin: 0 0 12px 0;
}

prompt {
  text-color: @accent;
}

entry {
  text-color: @fg;
}

listview {
  background-color: @bg;
  lines: 8;
  columns: 1;
  spacing: 6px;
}

element {
  background-color: transparent;
  text-color: @fg;
  border-radius: %dpx;
  padding: 8px;
}

element selected {
  background-color: @accent;
  text-color: @bg;
}

element-text {
  background-color: transparent;
  text-color: inherit;
}
]],
    theme.colors.bg,
    theme.colors.bg_alt,
    theme.colors.fg,
    theme.colors.muted,
    theme.colors.accent,
    theme.fonts.ui,
    theme.fonts.size,
    theme.rofi.width,
    theme.rofi.border_width,
    theme.rofi.border_radius,
    theme.rofi.border_radius,
    theme.rofi.border_radius
  )
end

return generate
