-- theme/render.lua

local function get_path(tbl, path)
	local value = tbl 

	for key in path:gmatch("[^.]+") do
		value = value[key]

		if value == nil then
			error("Missing template value: " .. path)
		end 
	end 

	return tostring(value) 
end 

local function generated_header(style)
	local lines = {
		"Generated by theme/build.lua",
		"Do not edit this file directly.",
		"Edit the source template or theme file instead.",
	}

	if style == "hash" then 
		return table.concat({
			"# " .. lines[1],
			"# " .. lines[2],
			"# " .. lines[3],
		}, "\n") .. "\n\n"
	end 

	if style == "semicolon" then
		return table.concat({
			"; " .. lines[1], 
			"; " .. lines[2],
			"; " .. lines[3], 
		}, "\n") .. "\n\n"
	end 
	if style == "css" then 
		return table.concat({
			"/*", 
			" * " .. lines[1],
			" * " .. lines[2],
			" * " .. lines[3], 
			" */",
		}, "\n") .. "\n\n"
	end 

	error("Unknown comment style: " .. tostring(style))
end 

local function add_generated_header(rendered, comment_style)
        local header = generated_header(comment_style)

        local shebang = rendered:match("^(#![^\n]*\n)")
        if shebang then
                local rest = rendered:sub(#shebang + 1)
                return shebang .. "\n" .. header .. rest
        end

        return header .. rendered
end

local function generate_i3_workspaces(theme)
	local define = {}
	local switch = {}
	local move = {}

	for _, ws in ipairs(theme.workspaces) do
		table.insert(define, "set $ws" .. ws.key .. " \"" .. ws.name .. "\"")
		table.insert(switch, "bindsym $mod+" .. ws.key .. " workspace number $ws" .. ws.key)
		table.insert(move, "bindsym $mod+Shift+" .. ws.key .. " move container to workspace number $ws" .. ws.key)
	end 

	return {
		define = table.concat(define, "\n"),
		switch = table.concat(switch, "\n"),
		move = table.concat(move, "\n"),
	}
end 

local function prepare_theme(theme)
	theme.computed = theme.computed or {}
	theme.generated = theme.generated or {}

	theme.computed.i3_top_gap = theme.polybar.height + theme.polybar.offset_y + 5 

	theme.generated.i3 = {
		workspaces = generate_i3_workspaces(theme), 
	}

	return theme 
end 

local function render_template(template, theme, comment_style)
	theme = prepare_theme(theme)

	local rendered = template:gsub("{{([%w%._]+)}}", function(path)
		return get_path(theme, path)
	end)
	
	return add_generated_header(rendered, comment_style)
end 

return render_template
